"""init tables

Revision ID: 4ab6a86c0b38
Revises: 
Create Date: 2023-08-13 23:29:37.657023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab6a86c0b38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', 'current_state', name='user_state_unique')
    )
    op.create_table('user_subscribtion',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'channel_id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='user_subscribtion_unique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subscribtion')
    op.drop_table('user_state')
    # ### end Alembic commands ###
