# Generated by Django 4.2.2 on 2023-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('current_state', models.CharField(choices=[('subscribing', 'Subscribing'), ('subscribed', 'Subscribed'), ('default', 'Default')], max_length=32)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userstate',
            constraint=models.UniqueConstraint(fields=('user_id', 'current_state'), name='unique_state_per_user'),
        ),
    ]
